#!/usr/bin/env bash
# Generate YAML files from PKL sources.
# PKL sources in pkl/ are the source of truth; YAML in values/, secrets/, services/ is generated.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEVOPS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PKL_DIR="$DEVOPS_DIR/pkl"
HEADER="# GENERATED BY PKL — DO NOT EDIT MANUALLY"
ERRORS=0

if ! command -v pkl &> /dev/null; then
    echo "ERROR: pkl is not installed."
    echo "  macOS:  brew install pkl"
    echo "  Linux:  https://pkl-lang.org/main/current/pkl-cli/index.html#installation"
    exit 1
fi

while IFS= read -r -d '' pkl_file; do
    rel_path="${pkl_file#"$PKL_DIR/"}"
    output_path="$DEVOPS_DIR/${rel_path%.pkl}.yaml"

    mkdir -p "$(dirname "$output_path")"

    if content=$(pkl eval -f yaml "$pkl_file" 2>&1); then
        {
            echo "$HEADER"
            echo "$content"
        } > "$output_path"
        echo "  ok  $rel_path → ${output_path#"$DEVOPS_DIR/"}"
    else
        echo "FAIL  $rel_path"
        echo "$content"
        ((ERRORS++)) || true
    fi
done < <(find "$PKL_DIR" -name "*.pkl" ! -path "*/schemas/*" -print0 | sort -z)

echo ""
if [ "$ERRORS" -gt 0 ]; then
    echo "FAILED: $ERRORS file(s) had errors."
    exit 1
fi

echo "All YAML generated from PKL sources."
