"""initial schema

Revision ID: cd8b49b33eee
Revises: 
Create Date: 2026-03-29 19:31:49.632305

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd8b49b33eee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('key', name=op.f('uq_feature_flags_key'))
    )
    op.create_table('links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(length=12), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links'))
    )
    op.create_index(op.f('ix_links_org_id'), 'links', ['org_id'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_table('click_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('link_id', sa.Uuid(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], name=op.f('fk_click_events_link_id_links')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_click_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_events')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index(op.f('ix_links_org_id'), table_name='links')
    op.drop_table('links')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
