import { test, expect } from '@playwright/test';
import { LinksPage } from './base/LinksPage.js';

const TEST_PREFIX = `e2e-test-${Date.now()}`;

function testLink(suffix: string) {
  return {
    title: `${TEST_PREFIX}-${suffix}`,
    targetUrl: 'https://example.com',
  };
}

test.describe('Links page', () => {
  let linksPage: LinksPage;
  const createdShortCodes: string[] = [];

  test.beforeEach(async ({ page }) => {
    linksPage = new LinksPage(page);
    await linksPage.navigate();
  });

  test.afterAll(async ({ browser }) => {
    // Clean up any links created during the suite
    if (createdShortCodes.length === 0) return;
    const context = await browser.newContext({ storageState: 'storageState.json' });
    const page = await context.newPage();
    const cleanup = new LinksPage(page);
    await cleanup.navigate();
    for (const shortCode of createdShortCodes) {
      try {
        await cleanup.deleteLink(shortCode);
      } catch {
        // best-effort cleanup
      }
    }
    await context.close();
  });

  test('shows Links heading', async () => {
    await expect(linksPage.getHeading('Links')).toBeVisible();
  });

  test('create a link and see it in the table', async ({ page }) => {
    const link = testLink('create');
    await linksPage.createLink(link);

    // Find the newly created row — short code is generated by the server, find by title
    const row = page.getByRole('row').filter({ hasText: link.title });
    await expect(row).toBeVisible();

    // Record the short code for cleanup
    const shortCodeCell = row.getByRole('cell').nth(1);
    const shortCode = (await shortCodeCell.textContent()) ?? '';
    if (shortCode) createdShortCodes.push(shortCode.trim());
  });

  test('search filters the table', async ({ page }) => {
    await linksPage.searchLinks(TEST_PREFIX);
    // At minimum the table rendered without error
    await expect(page.getByRole('table')).toBeVisible();
    await linksPage.searchLinks('');
  });

  test('status filter buttons are functional', async ({ page }) => {
    await linksPage.filterByStatus('Active');
    await expect(page.getByRole('button', { name: 'Active', exact: true })).toBeVisible();

    await linksPage.filterByStatus('All');
    await expect(page.getByRole('button', { name: 'All', exact: true })).toBeVisible();
  });

  test('sort by Clicks column', async () => {
    await linksPage.sortBy('Clicks');
    // Second click reverses sort — just verify no crash
    await linksPage.sortBy('Clicks');
  });

  test('edit a link title', async ({ page }) => {
    const link = testLink('edit');
    await linksPage.createLink(link);

    const row = page.getByRole('row').filter({ hasText: link.title });
    await expect(row).toBeVisible();
    const shortCodeCell = row.getByRole('cell').nth(1);
    const shortCode = ((await shortCodeCell.textContent()) ?? '').trim();
    createdShortCodes.push(shortCode);

    const updatedTitle = `${link.title}-updated`;
    await linksPage.editLink(shortCode, { title: updatedTitle });

    await expect(page.getByRole('row').filter({ hasText: updatedTitle })).toBeVisible();
  });

  test('delete a link deactivates it (soft-delete)', async ({ page }) => {
    const link = testLink('delete');
    await linksPage.createLink(link);

    const row = page.getByRole('row').filter({ hasText: link.title });
    await expect(row).toBeVisible();
    const shortCodeCell = row.getByRole('cell').nth(1);
    const shortCode = ((await shortCodeCell.textContent()) ?? '').trim();
    createdShortCodes.push(shortCode);

    // Delete is a soft-delete: triggers deactivation, dialog closes, table refreshes
    await linksPage.deleteLink(shortCode);

    // Filtering by Active confirms the link is no longer active
    await linksPage.filterByStatus('Active');
    await expect(page.getByRole('row').filter({ hasText: shortCode })).not.toBeVisible();

    // Reset filter
    await linksPage.filterByStatus('All');
  });
});
