name: Email Package CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "packages/email/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/email.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/email/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/email.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: 1
  FORCE_COLOR: 1

jobs:
  ci:
    name: Lint, Type Check & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: astral-sh/setup-uv@v8.0.0
        with:
          enable-cache: true

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Lint
        run: make email:lint

      - name: Type Check
        run: make email:type:check

      - name: Unit Tests
        run: make email:test:unit
